spring:
  application:
    name: Springboot-Aws-Application
  datasource:
   #driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/awstest
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  profiles:
#    active:
#    - test
logging:
  file:
    name: C:/Users/Home/Desktop/logs/springbootapplication.log